Models/ErrorViewModel.cs
namespace aspnetcore_paytr_entegrasyon.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using aspnetcore_paytr_entegrasyon.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace aspnetcore_paytr_entegrasyon.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/OdemeSayfasiController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Specialized;
using System.Text.Json;
using System.Text;
using System.Security.Cryptography;
using System.Net;
using Newtonsoft.Json.Linq;

namespace aspnetcore_paytr_entegrasyon.Controllers
{
    public class OdemeSayfasiController : Controller
    {
        [HttpPost]
        public IActionResult PayTR()
        {
            string merchant_id = "id";
            string merchant_key = "key";
            string merchant_salt = "salt";

            string emailstr = "email@email.com"; // Müşterinizin email bilgisi
            int payment_amountstr = 100; // Toplam Siparis Tutarı
            string merchant_oid = Guid.NewGuid().ToString().Substring(0, 8).ToUpper().Replace("-", ""); // Eşsiz sipariş numarası
            string user_namestr = "Ad Soyad"; // Müşterinin adı soyadı
            string user_addressstr = "Adres"; // Müşterinin adresi
            string user_phonestr = "Telefon"; // Müşterinin telefonu
            string merchant_ok_url = "https://" + Request.Host + "/OdemeSayfasi/Basarili"; // Başarılı sonuçlanırsa yönlenecek bilgi adresi (siparis onaylama adresi değil)
            string merchant_fail_url = "https://" + Request.Host + "/OdemeSayfasi/Basarisiz"; // Başarısız sonuçlanırsa yönlenecek bilgi adresi (siparis reddetme adresi değil)
            string user_ip = "999.999.999.999"; // Müşterinin ip adresi

            // Örnek sepet 
            object[][] user_basket = {
            new object[] {"Örnek ürün 1", "18.00", 1}, // 1. ürün (Ürün Ad - Birim Fiyat - Adet)
            new object[] {"Örnek ürün 2", "33.25", 2}, // 2. ürün (Ürün Ad - Birim Fiyat - Adet)
            new object[] {"Örnek ürün 3", "45.42", 1}, // 3. ürün (Ürün Ad - Birim Fiyat - Adet)
            };

            string timeout_limit = "30"; // islem zaman asımı süresi (dakika cinsinden)
            string debug_on = "1"; // debug mod
            string test_mode = "1"; // test mod
            string no_installment = "0"; // taksit
            string max_installment = "0"; // ekranda görülecek taksit adedi
            string currency = "TL"; // para birimi
            string lang = ""; // dil

            NameValueCollection data = new NameValueCollection();
            data["merchant_id"] = merchant_id;
            data["user_ip"] = user_ip;
            data["merchant_oid"] = merchant_oid;
            data["email"] = emailstr;
            data["payment_amount"] = payment_amountstr.ToString();

            string user_basket_json = JsonSerializer.Serialize(user_basket.ToArray());
            string user_basketstr = Convert.ToBase64String(Encoding.UTF8.GetBytes(user_basket_json));
            data["user_basket"] = user_basketstr;

            string Birlestir = string.Concat(merchant_id, user_ip, merchant_oid, emailstr, payment_amountstr.ToString(), user_basketstr, no_installment, max_installment, currency, test_mode, merchant_salt);
            HMACSHA256 hmac = new HMACSHA256(Encoding.UTF8.GetBytes(merchant_key));
            byte[] b = hmac.ComputeHash(Encoding.UTF8.GetBytes(Birlestir));
            data["paytr_token"] = Convert.ToBase64String(b);
            data["debug_on"] = debug_on;
            data["test_mode"] = test_mode;
            data["no_installment"] = no_installment;
            data["max_installment"] = max_installment;
            data["user_name"] = user_namestr;
            data["user_address"] = user_addressstr;
            data["user_phone"] = user_phonestr;
            data["merchant_ok_url"] = merchant_ok_url;
            data["merchant_fail_url"] = merchant_fail_url;
            data["timeout_limit"] = timeout_limit;
            data["currency"] = currency;
            data["lang"] = lang;

            TempData["merchant_oid"] = merchant_oid;

            try
            {
                using (WebClient client = new WebClient())
                {
                    client.Headers.Add("Content-Type", "application/x-www-form-urlencoded");
                    byte[] result = client.UploadValues("https://www.paytr.com/odeme/api/get-token", "POST", data);
                    string ResultAuthTicket = Encoding.UTF8.GetString(result);
                    dynamic json = JValue.Parse(ResultAuthTicket);

                    if (json.status == "success")
                    {
                        ViewBag.tokenData = "https://www.paytr.com/odeme/guvenli/" + json.token;
                    }
                    else
                    {
                        TempData["sonuc"] = "PAYTR IFRAME failed. reason:" + json.reason + "";
                    }
                }
            }
            catch (Exception x)
            {
                TempData["sonuc"] = x.Message.ToString();
            }

            return View();
        }

        [HttpPost]
        public IActionResult GeriDonusPayTR()
        {
            string merchant_key = "key";
            string merchant_salt = "salt";

            string merchant_oid = Request.Form["merchant_oid"];
            string status = Request.Form["status"];
            string total_amount = Request.Form["total_amount"];
            string hash = Request.Form["hash"];

            string Birlestir = string.Concat(merchant_oid, merchant_salt, status, total_amount);
            HMACSHA256 hmac = new HMACSHA256(Encoding.UTF8.GetBytes(merchant_key));
            byte[] b = hmac.ComputeHash(Encoding.UTF8.GetBytes(Birlestir));
            string token = Convert.ToBase64String(b);

            if (hash.ToString() != token)
            {
                TempData["gelen"] = "PAYTR notification failed: bad hash";
            }

            if (status == "success")
            { 
                //Ödeme Onaylandı
                TempData["gelen"] = "OK";
                // siparisi burada onaylayabilirsiniz
            }
            else
            { 
                //Ödemeye Onay Verilmedi
                TempData["gelen"] = "OK";
                // siparisi burada reddedebilirsiniz.
            }

            return View();

        }



    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <b class="display-4">Demo ödeme sayfası için aşağıdaki butona tıklayın</b>
    <br></br>
    <form method="post" asp-action="PayTR" asp-controller="OdemeSayfasi"><button>Post</button></form>
</div>

Views/OdemeSayfasi/GeriDonusPayTR.cshtml
@{
    Layout = null;
}

@TempData["gelen"]

Views/OdemeSayfasi/PayTR.cshtml
@{
    ViewData["Title"] = "PayTR";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="https://www.paytr.com/js/iframeResizer.min.js"></script>

<script>iFrameResize({}, '#paytriframe');</script>


<main class="main">
    <div class="page-content mb-10">
        <div class="container-fluid">
            <div>
                @TempData["sonuc"]
                <iframe src='@ViewBag.tokenData' frameborder="0" scrolling="no" style="width: 100%; overflow: auto; min-height: 600px; height: 550px;"></iframe>
            </div>
        </div>

    </div>
</main>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - aspnetcore_paytr_entegrasyon</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/aspnetcore_paytr_entegrasyon.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">aspnetcore_paytr_entegrasyon</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - aspnetcore_paytr_entegrasyon - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>